AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/EndOfLine:
  Enabled: false

